name: Deploy via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --no-progress --no-interaction

      - name: Create .env.local
        run: |
          echo "APP_ENV=prod" >> .env.local
          echo "APP_DEBUG=0" >> .env.local
          echo "DATABASE_URL=${{ secrets.ENV_DATABASE_URL }}" >> .env.local
          echo "APP_SECRET=${{ secrets.ENV_APP_SECRET }}" >> .env.local

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_HOST }}
          port: ${{ secrets.FTP_PORT }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: "./"
          remote_path: ${{ secrets.FTP_BASE_DIR }}
          delete_remote_files: false
